app:
  environment: local


spring:
  datasource:
    url: "jdbc:trino://localhost:8080/gold"
    username: admin
  kafka:
    bootstrap-servers: 'localhost:9092'
    schema-registry-url: 'mock://mock'
    security:
      protocol: 'PLAINTEXT'

server:
  port: 9091